import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Headers from "./Componant/Headers/page";
import Start from "./Componant/start/page";
import Hero from "./Componant/Hero/page";
import OurBlog from "./Componant/OurBlog/page";
import OurCustomrs from "./Componant/OurCustomrs/page";
import OurService from "./Componant/OurService/page";
import OurVision from "./Componant/OurVision/page";
import OurOffers from "./Componant/OurOffers/page";
import OurSeen from "./Componant/OurSeen/page";
import Footer from "./Componant/Footer/page";





const geistSans = localFont( {
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
} );
const geistMono = localFont( {
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
} );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body className={`${ geistSans.variable } ${ geistMono.variable } antialiased`}>
        <Headers />
        <Start />
        <Hero/>
        <OurBlog />
        <OurCustomrs />
        <OurService />
        <OurVision />
        <OurOffers />
        <OurSeen />
        <Footer />
        {children}
      </body>
    </html>
  );
}
