import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Headers from "./Componant/Headers/page";
import Start from "./Componant/start/page";
import Section3 from "./Componant/Hero/page";
import Section4 from "./Componant/OurBlog/page";
import Section5 from "./Componant/Section5/page";
import Section6 from "./Componant/OurService/page";
import Section7 from "./Componant/OurVision/page";
import Section8 from "./Componant/OurOffers/page";
import Section9 from "./Componant/OurSeen/page";
import Footer from "./Componant/Footer/page";





const geistSans = localFont( {
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
} );
const geistMono = localFont( {
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
} );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body className={`${ geistSans.variable } ${ geistMono.variable } antialiased`}>
        <Headers />
        <Start />
        <Section3 />
        <Section4 />
        <Section5 />
        <Section6 />
        <Section7 />
        <Section8 />
        <Section9 />
        <Footer />
        {children}
      </body>
    </html>
  );
}
